#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mongo:4.4 AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["ATTM_API.csproj", ""]
RUN dotnet restore "./ATTM_API.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "ATTM_API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "ATTM_API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ATTM_API.dll"]